import { MissingIngredient, Recipe } from '../types';

export function downloadFile(filename: string, text: string, mimeType: string = 'text/plain') {
  const element = document.createElement('a');
  const file = new Blob([text], { type: mimeType });
  element.href = URL.createObjectURL(file);
  element.download = filename;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

export function exportShoppingListAsCSV(missingIngredients: MissingIngredient[], recipeTitle: string): void {
  const headers = ['Ingredient Name', 'Estimated Quantity', 'Estimated Price (INR)'];
  const rows = missingIngredients.map((item) => [
    `"${item.name.replace(/"/g, '""')}"`,
    `"${item.estimated_quantity.replace(/"/g, '""')}"`,
    `₹${item.estimated_price_inr}`,
  ]);

  const totalCost = missingIngredients.reduce((sum, item) => sum + item.estimated_price_inr, 0);
  rows.push(['"TOTAL ESTIMATED COST"', '""', `"₹${totalCost}"`]);

  const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const filename = `Fridge2Feast_ShoppingList_${recipeTitle.toLowerCase().replace(/[^a-z0-9]/g, '_')}.csv`;
  downloadFile(filename, csvContent, 'text/csv;charset=utf-8;');
}

export function exportShoppingListAsTXT(missingIngredients: MissingIngredient[], recipeTitle: string): void {
  const totalCost = missingIngredients.reduce((sum, item) => sum + item.estimated_price_inr, 0);
  const lines = [
    `========================================`,
    `FRIDGE2FEAST AI - SMART SHOPPING LIST`,
    `Recipe: ${recipeTitle}`,
    `Generated on: ${new Date().toLocaleDateString()}`,
    `========================================`,
    ``,
    `MISSING INGREDIENTS TO PURCHASE:`,
    ...missingIngredients.map(
      (item, index) => `${index + 1}. ${item.name} (${item.estimated_quantity}) - Approx. ₹${item.estimated_price_inr}`
    ),
    ``,
    `----------------------------------------`,
    `TOTAL ESTIMATED SHOPPING COST: ₹${totalCost}`,
    `----------------------------------------`,
    `Happy cooking with Fridge2Feast AI!`,
  ];

  const filename = `Fridge2Feast_ShoppingList_${recipeTitle.toLowerCase().replace(/[^a-z0-9]/g, '_')}.txt`;
  downloadFile(filename, lines.join('\n'));
}

export function exportShoppingListAsMD(missingIngredients: MissingIngredient[], recipeTitle: string): void {
  const totalCost = missingIngredients.reduce((sum, item) => sum + item.estimated_price_inr, 0);
  const lines = [
    `# 🛒 Smart Shopping List - ${recipeTitle}`,
    `*Generated by Fridge2Feast AI on ${new Date().toLocaleDateString()}*`,
    ``,
    `## Missing Ingredients`,
    ...missingIngredients.map(
      (item) => `- [ ] **${item.name}** (${item.estimated_quantity}) — ~₹${item.estimated_price_inr}`
    ),
    ``,
    `**Total Estimated Shopping Cost:** ₹${totalCost}`,
  ];

  const filename = `Fridge2Feast_ShoppingList_${recipeTitle.toLowerCase().replace(/[^a-z0-9]/g, '_')}.md`;
  downloadFile(filename, lines.join('\n'), 'text/markdown');
}

export function exportRecipeAsMarkdown(recipe: Recipe): void {
  const md = `# ${recipe.title} (${recipe.badge})
*${recipe.short_description}*

- **Cuisine:** ${recipe.cuisine}
- **Difficulty:** ${recipe.difficulty}
- **Cooking Time:** ${recipe.cooking_time_minutes} mins
- **Servings:** ${recipe.servings}
- **Ingredient Utilization:** ${recipe.ingredient_utilization_percentage}%
- **Estimated Missing Cost:** ₹${recipe.estimated_missing_cost_inr}

---

## 🥗 Ingredients You Have
${recipe.ingredients_available.map((i) => `- [x] ${i.name} (${i.quantity})`).join('\n')}

## 🛒 Missing Ingredients to Buy
${recipe.ingredients_missing.map((m) => `- [ ] ${m.name} (${m.estimated_quantity}) - ~₹${m.estimated_price_inr}`).join('\n')}

---

## 👩‍🍳 Preparation & Cooking Steps
${recipe.preparation_steps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

---

## 💡 Chef Tips
${recipe.cooking_tips.map((tip) => `- ${tip}`).join('\n')}

## 🔄 Smart Substitutions
${recipe.substitutions.map((s) => `- **${s.original}** -> ${s.substitute}: ${s.note}`).join('\n')}

## 💚 Food Waste Impact
> ${recipe.food_waste_note}

---
*Generated by Fridge2Feast AI - Turn What's Left Into What's Next.*
`;

  const filename = `${recipe.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_recipe.md`;
  downloadFile(filename, md, 'text/markdown');
}
