import pandas as pd
from typing import List, Dict, Any

def export_shopping_list_csv(missing_ingredients: List[Dict[str, Any]], recipe_title: str) -> str:
    """
    Generates CSV string for missing ingredients shopping list.
    """
    data = []
    for item in missing_ingredients:
        data.append({
            "Recipe": recipe_title,
            "Missing Ingredient": item.get("name", ""),
            "Quantity Needed": item.get("estimated_quantity", "1 item"),
            "Estimated Price (INR ₹)": item.get("estimated_price_inr", 0.0)
        })
    df = pd.DataFrame(data)
    return df.to_csv(index=False)

def export_shopping_list_txt(missing_ingredients: List[Dict[str, Any]], recipe_title: str) -> str:
    """
    Generates plain TXT string for shopping list.
    """
    lines = [
        f"FRIDGE2FEAST AI - SMART SHOPPING LIST",
        f"Target Recipe: {recipe_title}",
        f"=" * 40,
        ""
    ]
    total = 0.0
    for idx, item in enumerate(missing_ingredients, 1):
        name = item.get("name", "Item")
        qty = item.get("estimated_quantity", "1 item")
        price = float(item.get("estimated_price_inr", 0.0))
        total += price
        lines.append(f"{idx}. {name} - {qty} (Est. ₹{price:.2f})")

    lines.append("")
    lines.append(f"-" * 40)
    lines.append(f"TOTAL ESTIMATED SHOPPING COST: ₹{total:.2f} INR")
    lines.append("Generated by Fridge2Feast AI - Turn What's Left Into What's Next.")
    return "\n".join(lines)

def export_shopping_list_markdown(missing_ingredients: List[Dict[str, Any]], recipe_title: str) -> str:
    """
    Generates Markdown string for recipe & shopping list.
    """
    lines = [
        f"# 🛒 Fridge2Feast AI Smart Shopping List",
        f"**Recipe:** {recipe_title}\n",
        f"| # | Ingredient | Quantity | Est. Price (INR ₹) |",
        f"|---|---|---|---|"
    ]
    total = 0.0
    for idx, item in enumerate(missing_ingredients, 1):
        name = item.get("name", "")
        qty = item.get("estimated_quantity", "")
        price = float(item.get("estimated_price_inr", 0.0))
        total += price
        lines.append(f"| {idx} | **{name}** | {qty} | ₹{price:.2f} |")

    lines.append(f"\n**Total Estimated Cost:** ₹{total:.2f} INR")
    lines.append("\n*Generated with Fridge2Feast AI Culinary Intelligence*")
    return "\n".join(lines)
