[server]
port = 3000
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10

[theme]
primaryColor = "#C84B31"
backgroundColor = "#FBF8F1"
secondaryBackgroundColor = "#F3EEDF"
textColor = "#2D3425"
font = "serif"

[browser]
gatherUsageStats = false
